#'This is a very simple example dataset generated by rnorm().
#'The data is random.
#'
#'The z-test function is not limited to this dataset; this is just a simple example
#'with 100 data points, a mean of 15, and standard deviation of 3.
#'
#'@format univariate
#'


data <- rnorm(100, 15, 3)
